#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

###################################################################
#Script Name	:cheat
#Description	:checks your custom cheatsheets
#Usage        :cheat <keyword> (eg cheat vim, cheat tmux, etc)
#Todos        :input validation, error checking
###################################################################

CS_DIR=~/cheatsheets/*

# Check for user input, if not, ask user for what cheatsheet they need
if [[ $# < 1 ]]; then
  read -p "What cheatsheet are you looking for? " CS_NAME
else
  CS_NAME=$1
echo "Looking for cheatsheet with keyword: $CS_NAME"
fi

# Look for directory and match cheatsheet
REGEX=".*${CS_NAME}.*"
MATCH=()

for FILE in $CS_DIR; do
  if [[ $FILE =~ $REGEX ]]; then
    # echo "Found: $FILE"
    MATCH+=($FILE)
  fi
done

# echo "**DEBUG** MATCH = ${MATCH[@]}"

if [[ ${#MATCH[@]} -eq 0 ]]; then
  echo "Nothing found in $CS_DIR that matched keyword: $CS_NAME"
  ls $CS_DIR
elif [[ ${#MATCH[@]} -eq 1 ]]; then
  less ${MATCH[0]}
else
  echo "Found ${#MATCH[@]} matches..."
  COUNTER=0
  for i in "${MATCH[@]}"; do
    echo "[$COUNTER] $i"
    ((COUNTER++))
  done
  echo "Enter the number corresponding to the cheatsheet you want "
  read ans

  echo "DEBUG: $ans"
  echo "MATCH: ${MATCH[ans]}"
  
  less ${MATCH[ans]}
  
 # if [[ $# > 0 ]]; then
 #   less ${MATCH[ans]}
 # fi
fi
